spring:
  application:
    name: thinkstep-test-online_users
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/onlineusers
    username: root
    password: password

logs:
  apache:
    folder: "/Users/aldrocha/others/workspaces/thinkstep/apache-logs"
    encoding: "UTF-8"
    initialOffset: 0
    scheduller:
      cronexp: "* * * * * *"

reactor:
  pool:
    size: 10

server:
  port: 8080
  error.whitelabel.enabled: true

logging:
  level:
    com:
     thinkstep: INFO

