spring:
  application:
    name: thinkstep-test-online_users
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/onlineusers
    username: root
    password: password
  datasourcelocal:
    url: jdbc:h2:mem:onlineusers
    username: root
    password: password
  cache:
    cache-names: logs, consolidations
    jcache:
      config=classpath:ehcache:
        xml: ehcache.xml
  h2:
    console:
      enabled=true:


logs:
  apache:
    folder: /thinkstep/apache-logs
    encoding: "UTF-8"
    initialOffset: 0
    scheduller:
      cronexp: "* */1 * * * *"
    regex: "^(\\S+) (\\S+) (\\S+) \\[([\\w:/]+\\s[+\\-]\\d{4})\\] \"(\\S+)\\s?(\\S+)?\\s?(\\S+)?\" (\\d{3}|-) (\\d+|-)\\s?\"?([^\"]*)\"?\\s?\"?([^\"]*)?\"?$"

reactor:
  pool:
    size: 10

server:
  port: 8080
  error.whitelabel.enabled: true

logging:
  level:
    com:
     thinkstep: INFO

